name: inventarioaptos
description: Aplicación Flutter para gestionar inventarios de apartamentos sin conexión.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  path_provider: ^2.0.15
  uuid: ^3.0.7
  collection: ^1.17.2
  intl: ^0.18.1
  pdf: ^3.10.7
  printing: ^5.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
